config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'dashboard#index'

  get 'show/:id' => 'dashboard#show', as: :project_details

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @projects = Dashboard.all
  end

  def show
    @project = Dashboard.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<ul class="nav nav-pills">
  <li role="presentation"><a href="#home">Home</a></li>
  <li role="presentation"><a href="#about-me">About Me</a></li>
  <li role="presentation"><a href="#projects">Portfolio</a></li>
  <li role="presentation"><a href="#contact">Contact</a></li>
</ul>

<div id="home">
  <h1>Zachary Okuhara</h1>
  <h3></h3>
</div>

<div id="about-me">
  <p>
    stuff
  </p>
</div>


<div id="projects">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <% @projects.each do |project| %>
        <div class="thumbnail">
          <h3><%= project.name %></h3>
          <%= link_to project.name, project_details_path(id: project.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id="contact">
  Contact details</br>
  GitHub Page
</div>

app/views/dashboard/show.html.erb
<h1>Dashboard#show</h1>
<%= @project.name %>
</br>
<%= image_tag @project.photo %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>